from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.lib.units import inch

from datetime import datetime


styles = getSampleStyleSheet()


# --------------------------------------------------
# Custom Styles
# --------------------------------------------------

title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading = styles["Heading2"]

normal = styles["BodyText"]

small = styles["Normal"]
small.fontSize = 9


# --------------------------------------------------
# Footer
# --------------------------------------------------

def footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    canvas.drawString(
        40,
        25,
        "Generated by Basic VAPT Scanner v1.0"
    )

    canvas.drawRightString(
        560,
        25,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# --------------------------------------------------
# Main Function
# --------------------------------------------------

def generate_pdf(
    scan,
    findings,
    filename,
    ssl_info=None,
    headers=None
):

    if ssl_info is None:
        ssl_info = {}

    if headers is None:
        headers = []

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []

# ==========================================
# REPORT TITLE
# ==========================================

    story.append(
    Paragraph(
        "Basic VAPT Scanner Report",
        title_style
    )
)

    story.append(
    Spacer(1, 15)
)

    story.append(
    Paragraph(
        f"<b>Target:</b> {scan.target}",
        normal
    )
)

    story.append(
    Paragraph(
        f"<b>Scan Type:</b> {scan.scan_type}",
        normal
    )
)

    story.append(
    Paragraph(
        f"<b>Status:</b> {scan.status}",
        normal
    )
)

    story.append(
    Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
        normal
    )
)

    story.append(
    Spacer(1, 20)
)

    # ==========================================
    # EXECUTIVE SUMMARY
    # ==========================================

    

    high = sum(
        1 for f in findings
        if f["severity"] == "High"
    )

    medium = sum(
        1 for f in findings
        if f["severity"] == "Medium"
    )

    low = sum(
        1 for f in findings
        if f["severity"] == "Low"
    )

    story.append(
    Paragraph("<b>Summary</b>", heading)
)

    story.append(
    Spacer(1,8)
)

    story.append(
    Paragraph(
        f"Total Open Ports : {len(findings)}",
        normal
    )
)

    story.append(
    Paragraph(
        f"High Severity : {high}",
        normal
    )
)

    story.append(
    Paragraph(
        f"Medium Severity : {medium}",
        normal
    )
)

    story.append(
    Paragraph(
        f"Low Severity : {low}",
        normal
    )
)

    story.append(
        Spacer(1,15)
    )
    # ==========================================
    # SSL / TLS INFORMATION
    # ==========================================

    story.append(
        Paragraph("<b>SSL / TLS Information</b>", heading)
    )

    story.append(
        Spacer(1,8)
    )

    if ssl_info and ssl_info.get("enabled"):
        story.append(
            Paragraph(
                f"SSL Enabled : Yes",
                normal
            )
        )

        story.append(
            Paragraph(
                f"TLS Version : {ssl_info.get('tls_version','Unknown')}",
                normal
            )
        )

        story.append(
            Paragraph(
                f"Issuer : {ssl_info.get('issuer','Unknown')}",
                normal
            )
        )

        story.append(
            Paragraph(
                f"Expiry Date : {ssl_info.get('expires','Unknown')}",
                normal
            )
        )
    else:
        story.append(
            Paragraph(
                "SSL Information Not Available",
                normal
            )
        )

    story.append(
        Spacer(1,15)
    )


    # ==========================================
    # HTTP SECURITY HEADERS
    # ==========================================

    story.append(
        Paragraph("<b>HTTP Security Headers</b>", heading)
    )

    story.append(
        Spacer(1,8)
    )

    if headers:

        table_data = [
            ["Header", "Status"]
        ]

        for h in headers:

            table_data.append([
                h["header"],
                h["status"]
            ])

        table = Table(
            table_data,
            colWidths=[260,100]
        )

        table.setStyle(TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("BOTTOMPADDING",(0,0),(-1,0),8)

        ]))
        story.append(table)

    else:

        story.append(
            Paragraph(
                "No HTTP Security Header information available.",
                normal
            )
        )

    story.append(
            Spacer(1,15)
        )

    # ==========================================
    # OPEN PORTS
    # ==========================================

    story.append(
        Paragraph(
            "Open Ports & Findings",
            heading
        )
    )

    story.append(
        Spacer(1,10)
    )

    table_data = [

        [
            "Port",
            "Service",
            "Version",
            "Severity"
        ]

    ]

    for item in findings:

        table_data.append([

            item["port"],

            item["service"],

            item["version"],

            item["severity"]

        ])

    table = Table(
        table_data,
        colWidths=[60,100,180,90]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BACKGROUND",(0,1),(-1,-1),colors.beige),

        ("ALIGN",(0,0),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,0),10)

    ]))

    story.append(table)

    story.append(
        Spacer(1,20)
    )


    # ==========================================
    # VULNERABILITY DETAILS
    # ==========================================

    story.append(
        Paragraph(
            "Vulnerability Details",
            heading
        )
    )

    story.append(
        Spacer(1,10)
    )

    for item in findings:

        story.append(

            Paragraph(

                f"<b>Port:</b> {item['port']}",

                normal

            )

        )

        story.append(

            Paragraph(

                f"<b>Service:</b> {item['service']}",

                normal

            )

        )

        story.append(

            Paragraph(

                f"<b>Version:</b> {item['version']}",

                normal

            )

        )

        story.append(

            Paragraph(

                f"<b>Severity:</b> {item['severity']}",

                normal

            )

        )

        if item.get("risk"):

            story.append(

                Paragraph(

                    f"<b>Risk:</b> {item['risk']}",

                    normal

                )

            )

        if item.get("recommendation"):

            story.append(

                Paragraph(

                    f"<b>Recommendation:</b> {item['recommendation']}",

                    normal

                )

            )

        story.append(
            Spacer(1,15)
        )
            # ==========================================
    # Build PDF
    # ==========================================

    doc.build(
        story,
        onFirstPage=footer,
        onLaterPages=footer
    )